[package]
name = "portal"
version = "0.1.0"
edition = "2024"
default-run = "portal"

[dependencies]
anyhow = "1.0.97"
color-eyre = "0.6.3"
image = "0.25.5"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
ratatui-image = "5.0.0"
tui-tree-widget = "0.23.0"
