[package]
name = "portal_proto"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
serde = { workspace = true }

[build-dependencies]
tonic-build = "0.12.3"
